---
  name: "list_namespaces"
  entry_point: "generic_kubernetes_action.py"
  pack: "kubernetes"
  description: "List available namespaces."
  runner_type: run-python
  parameters:
    method_name:
      immutable: true
      type: string
      default: 'list_namespaces'
